"""add Department

Revision ID: 965537f23af3
Revises: 8a0a27e709d2
Create Date: 2024-10-01 21:26:13.265274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965537f23af3'
down_revision = '8a0a27e709d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
